graph LR
 B[输入图类型]
    B --> C{是否无向图}
    C -->|是| D[将邻接矩阵
    转换为对称矩阵]
    C -->|否| E[保持原矩阵]
    D --> F[输入路径长度m
    初始化结果矩阵为单位矩阵
    ]
    E --> F
    F --> H[循环m次]
    H --> I[矩阵乘法：
    结果矩阵 × 邻接矩阵]
    I --> J{是否完成m次}
    J -->|否| H
    J -->|是| K[输出结果矩阵]
